#!/usr/bin/env python3
"""
Build helper: convert any binary file into a C source file containing a
constant byte array.  Used by Meson to embed the WhisperDrop binary and
icon inside the installer at compile time.

Usage: embed_binary.py <input> <varname> <output.c>
"""
import sys


def main():
    if len(sys.argv) != 4:
        print(f"Usage: {sys.argv[0]} <input> <varname> <output.c>",
              file=sys.stderr)
        sys.exit(1)

    in_path  = sys.argv[1]
    varname  = sys.argv[2]
    out_path = sys.argv[3]

    with open(in_path, "rb") as f:
        data = f.read()

    with open(out_path, "w") as out:
        out.write("/* Auto-generated by embed_binary.py — do not edit. */\n")
        out.write("#include <stddef.h>\n\n")
        out.write(f"const unsigned char {varname}[] = {{\n")
        for i in range(0, len(data), 16):
            chunk = data[i : i + 16]
            out.write("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",\n")
        out.write("};\n\n")
        out.write(f"const size_t {varname}_len = {len(data)};\n")


if __name__ == "__main__":
    main()
